import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Montserrat } from "next/font/google";

const glacialIndifferenceBplPsa = localFont({
  src: [
    {
      path: './fonts/glacialindifferencebplpsa-bold-webfont.woff2',
      weight: '700',
      style: 'normal'
    },
    {
      path: './fonts/glacialindifferencebplpsa-italic-webfont.woff2',
      weight: '400',
      style: 'italic'
    },
    {
      path: './fonts/glacialindifferencebplpsa-regular-webfont.woff2',
      weight: '400',
      style: 'normal'
    }
  ],
  variable: '--font-glacial'
});

const lovelo = localFont({
  src:  './fonts/Lovelo-Black.woff2',
  variable: '--font-lovelo'
});

const monteserrat = Montserrat({
  weight: '700',
  subsets: ['latin'],
  variable: '--font-monteserrat'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${glacialIndifferenceBplPsa.variable} ${lovelo.variable} ${monteserrat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
