import type { Grievance } from "~/app/grievances/types";

export const EXAMPLE_GRIEVANCES: Grievance[] = [
  {
    id: 1,
    name: "Test #1",
    description: "Test description #1",
    category: "Pay",
    point_person: "Walter Reuther",
    escalations: [
      {
        id: 1,
        date: "2025-12-19",
        step: "Step #1",
        status: "Waiting to Schedule",
        date_due: "2026-01-02",
        hearing_date: "2025-12-31",
        deadline_missed: false,
        user: { id: 1, is_active: true, name: "Walter Reuther" },
      },
    ],
  },
  {
    id: 2,
    name: "Test #2",
    description: "Test description #2",
    category: "Pay",
    point_person: "Cesar Chavez",
    escalations: [
      {
        id: 2,
        date: "2025-12-19",
        step: "Step #1",
        status: "Waiting to Schedule",
        date_due: "2026-01-02",
        hearing_date: null,
        deadline_missed: false,
        user: { id: 2, is_active: true, name: "Cesar Chavez" },
      },
      {
        id: 3,
        date: "2025-12-21",
        step: "Step #1",
        status: "Scheduled",
        date_due: null,
        hearing_date: "2025-12-30",
        deadline_missed: false,
        user: { id: 2, is_active: true, name: "Cesar Chavez" },
      },
      {
        id: 4,
        date: "2025-12-31",
        step: "Step #1",
        status: "Waiting on Decision",
        date_due: "2026-01-08",
        hearing_date: null,
        deadline_missed: false,
        user: { id: 2, is_active: true, name: "Cesar Chavez" },
      },
      {
        id: 5,
        date: "2026-01-09",
        step: "Step #1",
        status: "Waiting to File",
        date_due: "2026-01-30",
        hearing_date: null,
        deadline_missed: false,
        user: { id: 2, is_active: true, name: "Cesar Chavez" },
      },
    ],
  },
  {
    id: 3,
    name: "Test #3",
    description: "Test description #3",
    category: "PTO",
    point_person: "Clara Lemlich",
    escalations: [],
  },
  {
    id: 4,
    name: "Test #4",
    description: "Test description #4",
    category: "PTO",
    point_person: "Walter Reuther",
    escalations: [
      {
        id: 6,
        date: "2026-01-10",
        step: "Step #2",
        status: "In Abeyance",
        date_due: null,
        hearing_date: null,
        deadline_missed: false,
        user: { id: 1, is_active: true, name: "Walter Reuther" },
      },
    ],
  },
];
