"""empty message

Revision ID: 51120f0ab3f5
Revises: 
Create Date: 2026-07-03 08:30:54.406669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51120f0ab3f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grievance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secondary_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['secondary_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grievance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('secondary_id')

    # ### end Alembic commands ###
