"""empty message

Revision ID: 87541009c2ee
Revises: 51120f0ab3f5
Create Date: 2026-07-03 14:02:19.843039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87541009c2ee'
down_revision = '51120f0ab3f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grievance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grievance', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
